#(c) CETC 2007
ROOTDIR=.
CC=g++

LOCAL_INSTALL=../install/
LOCAL_INCLUDE=./include
LIB_PATH=

LIBS=

INCLUDE=-I$(LOCAL_INSTALL)/include  -I$(LOCAL_INCLUDE)
CFLAGS = -g -Wall

SRCS=$(wildcard *.c)
SRCS+=$(wildcard *.cpp)
OBJS=$(patsubst %.c,%.o,$(SRCS))

default:all

%.o:%.cpp
	@echo compiling $@
	$(CC) $(WFLAGS) $(CFLAGS) $(INCLUDE) -c $<

all:test

test: $(OBJS)
	$(CC) -o test $(OBJS) $(LIB_PATH) $(LIBS) $(CFLAGS) $(INCLUDE)

PHONY: clean
clean:
	rm *.o -rf
	rm test -f
